# Generated by Django 2.1.1 on 2018-09-27 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revamp_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevampProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revamp_tool.Prices')),
                ('treatment_processes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revamp_tool.TreatmentProcesses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('waste_quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revamp_tool.WasteQuality')),
                ('waste_streams', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revamp_tool.WasteStreams')),
            ],
        ),
    ]
