# Generated by Django 2.1.1 on 2018-09-27 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revamp_tool', '0002_revampproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prices',
            name='name',
            field=models.CharField(default='bla', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prices',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='revampproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revampproject',
            name='name',
            field=models.CharField(default='bla', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revampproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='treatmentprocesses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentprocesses',
            name='name',
            field=models.CharField(default='bla', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentprocesses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wastequality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastequality',
            name='name',
            field=models.CharField(default='cla', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastequality',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wastestreams',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastestreams',
            name='name',
            field=models.CharField(default='bla', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastestreams',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
