# Generated by Django 2.1.1 on 2018-10-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revamp_tool', '0005_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revampproject',
            name='treatment_processes',
        ),
        migrations.RemoveField(
            model_name='revampproject',
            name='waste_quality',
        ),
        migrations.AddField(
            model_name='revampproject',
            name='fs_treatment_processes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='fs_tp', to='revamp_tool.TreatmentProcesses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revampproject',
            name='fs_waste_quality',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='fs_wq', to='revamp_tool.WasteQuality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revampproject',
            name='ss_treatment_processes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='ss_tp', to='revamp_tool.TreatmentProcesses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revampproject',
            name='ss_waste_quality',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='ss_wq', to='revamp_tool.WasteQuality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revampproject',
            name='sw_treatment_processes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sw_tp', to='revamp_tool.TreatmentProcesses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revampproject',
            name='sw_waste_quality',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sw_wq', to='revamp_tool.WasteQuality'),
            preserve_default=False,
        ),
    ]
