# Generated by Django 2.1.2 on 2018-10-25 10:31

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('revamp_tool', '0007_revamppage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revamppage',
            old_name='body',
            new_name='body_en',
        ),
        migrations.AddField(
            model_name='revamppage',
            name='body_es',
            field=wagtail.core.fields.RichTextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revamppage',
            name='title_es',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
