# Generated by Django 2.1.2 on 2018-10-26 11:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('revamp_tool', '0008_auto_20181025_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='revampproject',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revamp_tool.Location'),
        ),
        migrations.AlterField(
            model_name='revamppage',
            name='body_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
