# Generated by Django 2.1.2 on 2018-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp_tool', '0009_auto_20181026_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
