# Generated by Django 2.1.2 on 2018-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp_tool', '0010_auto_20181026_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='revampproject',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revampproject',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
