# Generated by Django 2.1.2 on 2018-12-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp_tool', '0013_auto_20181112_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
